# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c893b9a846aedb77ad21579fe0e8942f9e1a58363b4bf1600f40bb11fe8414a60c50cd493e2765549dc76800c57064940fbcc392346872782f2d6b1fe43f7ed3

test:
  secret_key_base: 524100557577ea0ba84760d3da4556e98f8fffe8413b19391d0de3e0331f36f119992f4f27ed349911980b76e5e9430dd24b43ed2417a820161f2ca4cd717944

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
